# Unique function in the pandas

In [1]:
import numpy as np 
import pandas as pd 


rng = np.random.RandomState(42)
data = pd.Series(rng.randint(0,10,4))
data

0    6
1    3
2    7
3    4
dtype: int32

In [2]:
#creating a pandas data frame with the help of the numpy randint 

data_2 = pd.DataFrame(rng.randint(0,10,(3,4)),columns= ['a','b','c','d'])

In [3]:
data_2

   a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [4]:
#so we can see actually we created the pandas with numpy series and we can see how they work together actually  they are like bread and butter

In [5]:
np.exp(data)#finding the expoential for the the value in the series

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
np.sin(data_2*np.pi/4)

          a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [14]:
np.cos(data_2*0)

     a    b    c    d
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [15]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')

In [16]:
area/population

Alaska             NaN
California    0.011060
New York           NaN
Texas         0.026303
dtype: float64

In [17]:
#since there was no parameter for the alaska and the New York we  can see rigth here it is giving a NaN error

In [18]:
#so these funciton work the explicit indexing not the implicit indexing

In [19]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [22]:
#to avoid the nan values 
A.add(B,fill_value = 0)#so here missing indices is completely avoided and so on

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [30]:
import pandas as pd 
A = pd.DataFrame(rng.randint(0,20,(2,2))
                , columns = list('AB'))
A

    A   B
0  18  11
1  19   2

In [29]:
list('MONU')#crazy

['M', 'O', 'N', 'U']

In [34]:
B = pd.DataFrame(rng.randint(0,20,(3,3)),columns = list('ABC'))

B

    A   B   C
0   8   1  19
1  14   6  11
2   7  14   2

In [35]:
A+B

      A     B   C
0  26.0  12.0 NaN
1  33.0   8.0 NaN
2   NaN   NaN NaN

In [37]:
A+B

      A     B   C
0  26.0  12.0 NaN
1  33.0   8.0 NaN
2   NaN   NaN NaN

In [38]:
A.add(B,fill_value=0)

      A     B     C
0  26.0  12.0  19.0
1  33.0   8.0  11.0
2   7.0  14.0   2.0

In [40]:
A.pow(B,fill_value = 0)#it is basically squarring the value to each other and powering 0 or either its other way is always zer0

              A     B    C
0  1.101996e+10  11.0  0.0
1  7.990067e+17  64.0  0.0
2  0.000000e+00   0.0  0.0

Operation between data frames and series

In [56]:
#performing on numpy array 
import numpy as np 
A = np.random.randint(0,10,(3,3))
A

array([[1, 9, 5],
       [4, 3, 5],
       [6, 2, 2]], dtype=int32)

In [57]:
A - A[0]

array([[ 0,  0,  0],
       [ 3, -6,  0],
       [ 5, -7, -3]], dtype=int32)

In [58]:
A-A[:]#it hust produce the copy of the data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
A

array([[1, 9, 5],
       [4, 3, 5],
       [6, 2, 2]], dtype=int32)