Indexing in the data science

In [3]:
import pandas as pd 
import numpy as np

In [4]:
# in the iloc we can use implicit indexing implicit inexing basically means indexing which under the cover the external  indexess

In [5]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [8]:
data['populations_density'] = data['pop']/data['area']#so basically population density is population divide by the area

In [9]:
data

              area       pop  populations_density
California  423967  38332521            90.413926
Texas       695662  26448193            38.018740
New York    141297  19651127           139.076746
Florida     170312  19552860           114.806121
Illinois    149995  12882135            85.883763

In [10]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [11]:
data.T

,California,Texas,New York,Florida,Illinois
area,4.239670e+05,6.956620e+05,1.412970e+05,1.703120e+05,1.499950e+05
pop,3.833252e+07,2.644819e+07,1.965113e+07,1.955286e+07,1.288214e+07
populations_density,9.041393e+01,3.801874e+01,1.390767e+02,1.148061e+02,8.588376e+01

In [12]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [14]:
data.T

,California,Texas,New York,Florida,Illinois
area,4.239670e+05,6.956620e+05,1.412970e+05,1.703120e+05,1.499950e+05
pop,3.833252e+07,2.644819e+07,1.965113e+07,1.955286e+07,1.288214e+07
populations_density,9.041393e+01,3.801874e+01,1.390767e+02,1.148061e+02,8.588376e+01

In [15]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [17]:
data.iloc[:3,:2]

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [20]:
data.iloc[:5,:3]

              area       pop  populations_density
California  423967  38332521            90.413926
Texas       695662  26448193            38.018740
New York    141297  19651127           139.076746
Florida     170312  19552860           114.806121
Illinois    149995  12882135            85.883763

In [21]:
data.shape

(5, 3)

In [25]:
#for doing the same type of indexing we have to use the explicit with the loc is only possible as loc donenot suport the implicity values

In [26]:
data.loc[:'Illinois',:'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [29]:
data.loc[data.populations_density > 100 , ['area'],['pop']]

IndexingError: Too many indexers

In [32]:
data.iloc[:,0] = 0
data

            area       pop  populations_density  (0, 0)
California     0  38332521            90.413926       0
Texas          0  26448193            38.018740       0
New York       0  19651127           139.076746       0
Florida        0  19552860           114.806121       0
Illinois       0  12882135            85.883763       0

In [33]:
data[1:3]

          area       pop  populations_density  (0, 0)
Texas        0  26448193            38.018740       0
New York     0  19651127           139.076746       0

In [36]:
data['Texas':'Florida']

          area       pop  populations_density  (0, 0)
Texas        0  26448193            38.018740       0
New York     0  19651127           139.076746       0
Florida      0  19552860           114.806121       0

In [40]:
#this type of indexing is called queries 
data[data['populations_density'] >100] #here we can also write some advanced level of query to get the projected answer from the data

          area       pop  populations_density  (0, 0)
New York     0  19651127           139.076746       0
Florida      0  19552860           114.806121       0