## Merging and join

In [1]:
#merging and join in the python pandas

In [2]:
#making a display function one more time

In [3]:
import pandas as pd 
import numpy as np

In [4]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self,*args):#storing all the arguments means variable etc 
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_()) for a in self.args)

    def _repr_(self):
        return '\n'.join(a+'\n'+repr(eval(a)) for a in self.args)

In [5]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering',
'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})

In [6]:
display('df1','df2')

In [7]:
df3 = pd.merge(df1,df2)

In [8]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [9]:
#so this was one to one join

In [10]:
#many to many join Many-to-many join

In [11]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})

In [12]:
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [13]:
display('df3','df4')

In [14]:
pd.merge(df3,df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [15]:
#here we can see that there is duplicates of the guido since there are more than one engenerring group guido was superviser as a whole so he will supervse both of them 
#that many on one merging works

In [16]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],
                'skills': ['math', 'spreadsheets', 'software', 'math',
'spreadsheets', 'organization']})

In [17]:
display('df1','df5')

In [18]:
pd.merge(df1,df5)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering      software
3     Jake  Engineering          math
4     Lisa  Engineering      software
5     Lisa  Engineering          math
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [19]:
#so till now we understood how one on one , many on one , and many to many  works in the pandas for merging the data frames which matches

In [20]:
#the speicification keys in the pandas 
pd.merge(df1,df5, on='group')

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering      software
3     Jake  Engineering          math
4     Lisa  Engineering      software
5     Lisa  Engineering          math
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [21]:
#if i have to explain it is simply we just telling on what basis you have to do this merging simple as that

In [22]:
#now merging on the different columns if the data frames are not in columns but the stuff feels same

In [23]:
"using left join and right join in the pandas"

'using left join and right join in the pandas'

In [24]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [25]:
df3_ = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})

In [26]:
df3_

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [27]:
display('df1','df3_'
       )

In [28]:
display('df1','df3_','pd.merge(df1,df3_,left_on = "employee" ,right_on = "name").drop("name",axis=1)')#so here we are just join on basis of common traits we are finding in the data

In [29]:
#left_index and right_index in the python pandas

In [30]:
#basically here we are not  joing on the basis of the coloumns but on the basis of the index

In [31]:
#for that we have tset the index first too get accurate result

In [32]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [33]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [38]:
#so here basically we are just replacing and default index to the employee column  that has been given in the data frames 
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

In [39]:
display('df1a','df2a')

In [43]:
#index based merging not on the basis of the columns or rows but just on the basis of the index that we get provided not provided we have made it ourself
display('df1a','df2a','pd.merge(df1a,df2a,left_index = True , right_index = True)')

In [44]:
df2a.join(df1a)#index based merging not the coloum based

          hire_date        group
employee
Lisa           2004  Engineering
Bob            2008   Accounting
Jake           2012  Engineering
Sue            2014           HR

### Specifiying the set arthimatics for the joins

In [45]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])

In [46]:
df6

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [47]:
df7

     name drink
0    Mary  wine
1  Joseph  beer

In [53]:
pd.merge(df6,df7)#here only one thing is common that why only mary is comming

   name   food drink
0  Mary  bread  wine

In [50]:
#trying the inner 
pd.merge(df6,df7,how='inner')

   name   food drink
0  Mary  bread  wine

In [51]:
#lets try outer ones so nan can be produced 
pd.merge(df6,df7,how='outer')

     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [52]:
#on the basis of the left 
pd.merge(df6,df7,how = "left")

    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [54]:
#overlapping  column names

In [55]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})

In [57]:
#so basically here we can see that there is conflicting columns names where there is two different types of ranks 
display('df8','df9','pd.merge(df8,df9,on="name")')

In [58]:
#here we seen a interseting things on the  basis that there was conflicting columns merge functoin itselt setted the values value_x and value_y on the basis of itself

In [60]:
#setting the suffix ourself 
pd.merge(df8,df9,on='name',suffixes = ['_L','_y'])

   name  rank_L  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

## Performing all these techniques on the us data

In [61]:
#Us data

In [63]:
#downloading the  data of the us from the git hub repository

In [64]:
pop = pd.read_csv('state-population.csv')
area = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

In [65]:
pop

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

In [66]:
area

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515

In [67]:
pop

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

In [68]:
area

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515

In [69]:
abbrevs

                   state abbreviation
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8   District of Columbia           DC
9                Florida           FL
10               Georgia           GA
11                Hawaii           HI
12                 Idaho           ID
13              Illinois           IL
14               Indiana           IN
15                  Iowa           IA
16                Kansas           KS
17              Kentucky           KY
18             Louisiana           LA
19                 Maine           ME
20               Montana           MT
21              Nebraska           NE
22                Nevada           NV
23         New Hampshire           NH
24            New Jersey           NJ
25            New Mexico           NM
26              New York           NY
27        North Carolina           NC
28          North Dakota           ND
29                  Ohio           OH
30              Oklahoma           OK
31                Oregon           OR
32              Maryland           MD
33         Massachusetts           MA
34              Michigan           MI
35             Minnesota           MN
36           Mississippi           MS
37              Missouri           MO
38          Pennsylvania           PA
39          Rhode Island           RI
40        South Carolina           SC
41          South Dakota           SD
42             Tennessee           TN
43                 Texas           TX
44                  Utah           UT
45               Vermont           VT
46              Virginia           VA
47            Washington           WA
48         West Virginia           WV
49             Wisconsin           WI
50               Wyoming           WY

In [71]:
display('pop.head()','area.head()','abbrevs.head()')

In [73]:
#the info we want to find  in this data is basically usa top states and the states name in 2010

In [76]:
merge = pd.merge(pop,abbrevs,how='outer',left_on = 'state/region', right_on = 'abbreviation')

In [77]:
merge

     state/region     ages  year  population    state abbreviation
0              AK    total  1990    553290.0   Alaska           AK
1              AK  under18  1990    177502.0   Alaska           AK
2              AK    total  1992    588736.0   Alaska           AK
3              AK  under18  1991    182180.0   Alaska           AK
4              AK  under18  1992    184878.0   Alaska           AK
...           ...      ...   ...         ...      ...          ...
2539           WY  under18  1993    137458.0  Wyoming           WY
2540           WY    total  1991    459260.0  Wyoming           WY
2541           WY  under18  1991    136720.0  Wyoming           WY
2542           WY  under18  1990    136078.0  Wyoming           WY
2543           WY    total  1990    453690.0  Wyoming           WY

[2544 rows x 6 columns]

In [78]:
#dropping the duplicate abbreviation 
merge  = merge.drop('abbreviation',axis = 1)

In [79]:
merge

     state/region     ages  year  population    state
0              AK    total  1990    553290.0   Alaska
1              AK  under18  1990    177502.0   Alaska
2              AK    total  1992    588736.0   Alaska
3              AK  under18  1991    182180.0   Alaska
4              AK  under18  1992    184878.0   Alaska
...           ...      ...   ...         ...      ...
2539           WY  under18  1993    137458.0  Wyoming
2540           WY    total  1991    459260.0  Wyoming
2541           WY  under18  1991    136720.0  Wyoming
2542           WY  under18  1990    136078.0  Wyoming
2543           WY    total  1990    453690.0  Wyoming

[2544 rows x 5 columns]

In [80]:
merge.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [83]:
#checking is there is any null values 
merge.isnull().any()#basically any functionn helps in getting if there is any in the columns wise rather  than full data frame table

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [85]:
#doing fancy indexing 
merge[merge['population'].isnull()].head()

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN