# Heirarchical indexing - Part-2

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#now we are going to do the MultiIndex for the columns

In [3]:
#creating heirarchical index for the index and columns 
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names= ['year','visit']
                                )
columns = pd.MultiIndex.from_product([['Bob','Suzy','Michael'],['HR','Temp']],
                                    names = ['Name','Type'])

In [6]:
#making a fake data 
data = np.round(np.random.randn(4,6),1)#here we are making an array of 4,6 size and rounding that to 1 digit
data[:,::2] *= 10
data += 37

In [7]:
#creating the data frame 
df = pd.DataFrame(data,index = index , columns = columns)

In [8]:
df

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      33.0  37.7  33.0  38.0    32.0  36.5
     2      31.0  37.5  38.0  37.7    35.0  37.1
2014 1      35.0  37.7  38.0  35.3    43.0  34.5
     2      48.0  38.7  38.0  36.5    51.0  39.8

In [9]:
df['Bob']

Type          HR  Temp
year visit
2013 1      33.0  37.7
     2      31.0  37.5
2014 1      35.0  37.7
     2      48.0  38.7

In [10]:
#indexing and slicing in multi index indices and columns