# Heirarchical indexing

In [1]:
import numpy as np 
import pandas as pd

In [2]:
#a multiply indexed series 
index = [('California', 2000), ('California', 2010),
('New York', 2000), ('New York', 2010),
('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
18976457, 19378102,
20851820, 25145561]

In [3]:
pop = pd.Series(populations,index = index )

In [4]:
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [5]:
pop[('California',2000):('Texas', 2010)]

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [6]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [7]:
pop[[i for i in pop.index if i[0] == 'California']]#this  a way of getting the desired result but it is not convient

(California, 2000)    33871648
(California, 2010)    37253956
dtype: int64

In [8]:
#better way to do it pandas multiply indexing

In [9]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [10]:
pop = pop.reindex(index
                 )

In [11]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [12]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [13]:
#Separating the data into two columns based on the information provided
pop_df = pop.unstack()
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [14]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [15]:
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [16]:
pop_df = pd.DataFrame({'total': pop,
'under18': [9267089, 9284094,
4687374, 4318033,
5906301, 6879014]})

In [17]:
pop_df

                    total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [18]:
pop_u18 = pop_df['under18']/pop_df['total']

In [19]:
pop_u18.unstack()

                2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [36]:
#Methods of multi index creation
data1 = np.random.randint(1,10,(1,4))
data2 = np.random.randint(1,10,(1,4))

In [37]:
#creating an multi index data frame
import pandas as pd 
df = pd.DataFrame(index = [['a','a','b','b'],[1,2,1,2]],
                 columns = ['data1','data2'])
data1 = np.random.randint(1,10,(1,4))

In [38]:
df

    data1 data2
a 1   NaN   NaN
  2   NaN   NaN
b 1   NaN   NaN
  2   NaN   NaN

In [39]:
data = {('California', 2000): 33871648,
('California', 2010): 37253956,
('Texas', 2000): 20851820,
('Texas', 2010): 25145561,
('New York', 2000): 18976457,
('New York', 2010): 19378102}

In [49]:
data4=pd.Series(data)#so here i can see that pandas automatically apply the multi indexing

In [50]:
data3 = pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

In [52]:
data4.reindex(data3)

a  1   NaN
   2   NaN
b  1   NaN
   2   NaN
dtype: float64

In [54]:
# #different types of multi index creation 
# pd.Multiindex.from array we have already done

In [55]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [58]:
pd.MultiIndex.from_product([['a','b'],[1,2,3]])

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3)],
           )

In [59]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [60]:
#we can also name the lable and the levels

In [61]:
#by doing this 
pop.index.names = ['state','year']

In [62]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [63]:
#multi index for the columns with the help of the medical report