In [61]:
import pandas as pd 
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
data = pd.Series([1,2,3,4,5])

In [4]:
data#series of the data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
data.values#it tell the values of  the function that we have putted in the array

array([1, 2, 3, 4, 5])

In [6]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
data[1]

np.int64(2)

In [8]:
data[:]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
data[1:2]#just like indexing in the numpy arrat

1    2
dtype: int64

In [10]:
series = pd.Series([1,2,3,4,5,6],
                  index=['a','b','c','d','e','f'])

In [11]:
series['a']#so here we did something interesting that we can also define the particular index in the data

np.int64(1)

In [12]:
series = pd.Series([1,2,3,4,5,6],
                  index=['a','b','c','d','e','f'])

In [13]:
series

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [14]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

In [15]:
#creating the seires 
popuation_series = pd.Series(population_dict)
popuation_series

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
popuation_series['California']

np.int64(38332521)

In [17]:
popuation_series[0:3]

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [18]:
popuation_series['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [19]:
#diff ways to create an pandas series 
series_2 = pd.Series(5,index = [1,2,3,4,5,6,7])#in pandas series is scalar values can repeat 
series_2

1    5
2    5
3    5
4    5
5    5
6    5
7    5
dtype: int64

In [20]:
students = {
    1: {"name": "Aarav", "marks": 85},
    2: {"name": "Diya", "marks": 92},
    3: {"name": "Ishaan", "marks": 74}
}

In [21]:
pd_3 = pd.Series(students)

In [22]:
pd_3

1     {'name': 'Aarav', 'marks': 85}
2      {'name': 'Diya', 'marks': 92}
3    {'name': 'Ishaan', 'marks': 74}
dtype: object

### Dataframes

In [23]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [42]:
population= pd.Series(area_dict)
population

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [43]:
states  = pd.DataFrame({'Population':popuation_series,
                             'area':area_dict})#here the index is overlapping so there is not error and also it is making a dataframes

In [44]:
states

            Population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [45]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [46]:
states.columns

Index(['Population', 'area'], dtype='object')

In [47]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [48]:
#so here like series both functoin can be performed as weel as as there are columns as they are added

In [49]:
states['area']#here we can see area is acting as key of the dictionary and returning the values in that key

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [50]:
#construction of the data frames from the scratch

In [56]:
#creating a data frame from the single series 
pd.DataFrame(population,columns=['population'])

            population
California      423967
Texas           695662
New York        141297
Florida         170312
Illinois        149995

In [57]:
#creating a data frame from the list of the dictionaries 
dict = [{'a':i , 'b' : 2*i} for i in range(3)]
pd.DataFrame(dict)

   a  b
0  0  0
1  1  2
2  2  4

In [62]:
#creating a data frame from the numpy array 
pd.DataFrame(np.random.rand(3,2),
            columns = ['1','2'],
            index = ['a','b','c'])

          1         2
a  0.173101  0.068493
b  0.740170  0.848486
c  0.574636  0.956837