## Merging and join

In [1]:
#merging and join in the python pandas

In [2]:
#making a display function one more time

In [3]:
import pandas as pd 
import numpy as np

In [20]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self,*args):#storing all the arguments means variable etc 
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_()) for a in self.args)

    def _repr_(self):
        return '\n'.join(a+'\n'+repr(eval(a)) for a in self.args)

In [21]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering',
'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})

In [22]:
display('df1','df2')

In [24]:
df3 = pd.merge(df1,df2)

In [25]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [26]:
#so this was one to one join

In [29]:
#many to many join Many-to-many join

In [30]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})

In [31]:
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [32]:
display('df3','df4')

In [33]:
pd.merge(df3,df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [34]:
#here we can see that there is duplicates of the guido since there are more than one engenerring group guido was superviser as a whole so he will supervse both of them 
#that many on one merging works

In [35]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],
                'skills': ['math', 'spreadsheets', 'software', 'math',
'spreadsheets', 'organization']})

In [36]:
display('df1','df5')

In [37]:
pd.merge(df1,df5)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering      software
3     Jake  Engineering          math
4     Lisa  Engineering      software
5     Lisa  Engineering          math
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [38]:
#so till now we understood how one on one , many on one , and many to many  works in the pandas for merging the data frames which matches

In [39]:
#the speicification keys in the pandas 
pd.merge(df1,df5, on='group')

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering      software
3     Jake  Engineering          math
4     Lisa  Engineering      software
5     Lisa  Engineering          math
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [40]:
#if i have to explain it is simply we just telling on what basis you have to do this merging simple as that

In [41]:
#now merging on the different columns if the data frames are not in columns but the stuff feels same

In [42]:
"using left join and right join in the pandas"

'using left join and right join in the pandas'

In [43]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [44]:
df3_ = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})

In [45]:
df3_

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [47]:
display('df1','df3_'
       )

In [55]:
display('df1','df3_','pd.merge(df1,df3_,left_on = "employee" ,right_on = "name").drop("name",axis=1)')#so here we are just join on basis of common traits we are finding in the data

In [57]:
#left_index and right_index in the python pandas

In [58]:
#basically here we are not  joing on the basis of the coloumns but on the basis of the index

In [59]:
#for that we have tset the index first too get accurate result