# Heirarchical indexing - Part-2

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#now we are going to do the MultiIndex for the columns

In [3]:
#creating heirarchical index for the index and columns 
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names= ['year','visit']
                                )
columns = pd.MultiIndex.from_product([['Bob','Suzy','Michael'],['HR','Temp']],
                                    names = ['Name','Type'])

In [4]:
#making a fake data 
data = np.round(np.random.randn(4,6),1)#here we are making an array of 4,6 size and rounding that to 1 digit
data[:,::2] *= 10
data += 37

In [5]:
#creating the data frame 
health_data = pd.DataFrame(data,index = index , columns = columns)

In [6]:
health_data

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      33.0  36.4  26.0  36.1    37.0  36.6
     2      22.0  37.0  39.0  35.9    37.0  37.2
2014 1      35.0  37.3  51.0  36.2    56.0  35.9
     2      44.0  37.4  45.0  38.0    27.0  36.7

In [7]:
#indexing and slicing in multi index indices and columns

In [8]:
health_data

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      33.0  36.4  26.0  36.1    37.0  36.6
     2      22.0  37.0  39.0  35.9    37.0  37.2
2014 1      35.0  37.3  51.0  36.2    56.0  35.9
     2      44.0  37.4  45.0  38.0    27.0  36.7

In [9]:
health_data[['Bob','Michael']]

Name         Bob       Michael
Type          HR  Temp      HR  Temp
year visit
2013 1      33.0  36.4    37.0  36.6
     2      22.0  37.0    37.0  37.2
2014 1      35.0  37.3    56.0  35.9
     2      44.0  37.4    27.0  36.7

In [10]:
health_data.iloc[:2,:2]

Name         Bob
Type          HR  Temp
year visit
2013 1      33.0  36.4
     2      22.0  37.0

In [11]:
#rearranging multi indexing

In [26]:
#creating an multi index
index2 = pd.MultiIndex.from_product([['a','b','c'],[1,2]])
data2 = pd.Series(np.random.rand(6),index = index2 )
data2.index.names = ['char','int']

In [27]:
data2

char  int
a     1      0.284388
      2      0.230402
b     1      0.235802
      2      0.691143
c     1      0.435035
      2      0.499850
dtype: float64

In [28]:
try: 
    data2['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

In [29]:
data2['a':'b']

char  int
a     1      0.284388
      2      0.230402
b     1      0.235802
      2      0.691143
dtype: float64

In [30]:
data2

char  int
a     1      0.284388
      2      0.230402
b     1      0.235802
      2      0.691143
c     1      0.435035
      2      0.499850
dtype: float64